### ISSUE TITLE
HTML file in attachments

### ISSUE THREAD

**Issue by SUHAR1K** [vladimarius/imapy#14]
HTML file in applications dose not downloaded

**Comment by vladimarius** [comment]
I need to reproduce this bug locally.
It would be nice if you could send me some sample email so i could check the parser.

**Comment by SUHAR1K** [comment]
I sent you a letter in the mail

**Comment by vladimarius** [comment]
Ok, i'll check it later today

**Comment by vladimarius** [comment]
when you select email message you want to process, html files will be contained inside
email['html']
For example:

```
import imapy
box = imapy.connect(...)
emails = box.folder('INBOX').emails(-1)
for html in emails[0].html:
    print html
```

**Comment by SUHAR1K** [comment]
Thanks
