### ISSUE TITLE
Email save attachment example

### ISSUE THREAD

**Issue by SUHAR1K** [vladimarius/imapy#15]
In email_save_attachment.py small error in "with open("file_name, 'w') as f:", downloaded files is empty, replace it to "with open("file_name, 'wb') as f:"

**Comment by vladimarius** [comment]
It really depends on what you are doing.

Citation from `https://docs.python.org/2/tutorial/inputoutput.html`:

_On Windows, 'b' appended to the mode opens the file in binary mode, so there are also modes like 'rb', 'wb', and 'r+b'. Python on Windows makes a distinction between text and binary files; the end-of-line characters in text files are automatically altered slightly when data is read or written. This behind-the-scenes modification to file data is fine for ASCII text files, but it’ll corrupt binary data like that in JPEG or EXE files. Be very careful to use binary mode when reading and writing such files. On Unix, it doesn’t hurt to append a 'b' to the mode, so you can use it platform-independently for all binary files._

**Comment by SUHAR1K** [comment]
Thanks
