### ISSUE TITLE
Search in subject error

### ISSUE THREAD

**Issue by SUHAR1K** [vladimarius/imapy#16]
I want to get email with some word in subject, i try:
 `folders = imap.folders()
    for folder in folders:
        q = Q()
        emails = imap.folder(folder).emails(
            q.flagged().subject("2")
            )`
but i get a error:

> Traceback (most recent call last):
>   File "C:\Users\Bi MOMMY\Desktop\ima.py", line 39, in <module>
>     main()
>   File "C:\Users\Bi MOMMY\Desktop\ima.py", line 20, in main
>     q.flagged().subject("2")
>   File "C:\Python35\lib\site-packages\imapy\imap.py", line 34, in wrapper
>     return func(_args, *_kwargs)
>   File "C:\Python35\lib\site-packages\imapy\imap.py", line 306, in emails
>     return self._fetch_emails_info(uids)
>   File "C:\Python35\lib\site-packages\imapy\imap.py", line 34, in wrapper
>     return func(_args, *_kwargs)
>   File "C:\Python35\lib\site-packages\imapy\imap.py", line 362, in _fetch_emails_info
>     result, data = self.imap.uid('FETCH', uids, '(FLAGS BODY.PEEK[])')
>   File "C:\Python35\lib\imaplib.py", line 863, in uid
>     typ, dat = self._simple_command(name, command, *args)
>   File "C:\Python35\lib\imaplib.py", line 1180, in _simple_command
>     return self._command_complete(name, self._command(name, *args))
>   File "C:\Python35\lib\imaplib.py", line 1011, in _command_complete
>     raise self.error('%s command error: %s %s' % (name, typ, data))
> imaplib.IMAP4.error: UID command error: BAD [b'[PARSE] Range parse error']

Whats wrong?

**Comment by n3storm** [comment]
It can be a problem that you are using Python3?
