### ISSUE TITLE
How to getting ALL UID List of selected folder?

### ISSUE THREAD

**Issue by jet10000** [vladimarius/imapy#23]
How to getting ALL UID List of selected folder?

Thanks

**Comment by mcepl** [comment]
Well, I guess ``emails = box.folder('Inbox').emails(q.since('1-Jan-1970')`` should work, but that's ugly.

**Comment by vladimarius** [comment]
Please check this example:
https://github.com/vladimarius/imapy/blob/master/examples/get_email_uids.py
