### ISSUE TITLE
Add port argument to IMAP.connect

### ISSUE THREAD

**Issue by RazerM** [vladimarius/imapy#4]
Some mail servers use non-default ports, this should be a keyword argument to `IMAP.connect()`.

If port isn't passed, you can use `imaplib.IMAP4_PORT` or `imaplib.IMAP4_SSL_PORT` depending on if `ssl` is set.

**Comment by woutervh** [comment]
See my changes:
https://github.com/WouterVH/imapy/commit/b5a83ce55e567c34a2877fd611198040eee910a4

**Comment by vladimarius** [comment]
Fixed in 1.1.0
